// utils/Constants.kt
package com.example.elocker.utils
val PUBLIC_KEY_FROM_SERVER = """
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDlNv516kOgukE++CPe0796IyPJnPecSYqS7yy3FPs7nFNtkGMKsSfYyLzdj6FTKvWWFcYPZtuRek5/Xv5rK1M6/WhhFAKM6DF5M3dMmQQANNi8gezsVdhzMlgSzfttE356YZnltJz4lo3d5PlILplKtfX/H2WL4Xbe3glviJpwxwIDAQAB
""".trimIndent()